# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       heliumreborn

# >> macros
# << macros

Summary:    Helium Mobile browser ported to MeeGo Qt Quick Components
Version:    1.1.4
Release:    1
Group:      System/Libraries
License:    LGPL v2.1
URL:        https://github.com/nemomobile/heliumreborn
Source0:    %{name}-%{version}.tar.bz2
Source1:    heliumreborn.desktop
Source2:    portrait.png
Source3:    landscape.png
Source100:  heliumreborn.yaml
Requires:   /usr/bin/update-desktop-database
Requires:   libqtwebkit-qmlwebkitplugin
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  desktop-file-utils

%description
Helium Mobile browser ported to Qt Quick Components for Nemo Mobile.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake  \
    MEEGO_VERSION_MAJOR=1 \
    MEEGO_VERSION_MINOR=2 \
    MEEGO_VERSION_PATCH=0 \
    MEEGO_EDITION=harmattan \
    DEFINES+=MEEGO_EDITION_HARMATTAN

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/%{_bindir}
mkdir -p %{buildroot}/%{_datadir}/applications
mkdir -p %{buildroot}/opt/heliumreborn
cp %{SOURCE1} %{buildroot}/%{_datadir}/applications/heliumreborn.desktop
cp %{SOURCE2} %{buildroot}/opt/heliumreborn/
cp %{SOURCE3} %{buildroot}/opt/heliumreborn/
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# >> post
/usr/bin/update-desktop-database -q
# << post

%postun
# >> postun
/usr/bin/update-desktop-database -q
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}/heliumreborn
%{_datadir}/applications/heliumreborn.desktop
/opt/heliumreborn/landscape.png
/opt/heliumreborn/portrait.png
# >> files
# << files
